language: go
env:
- GIMME_OS=linux GIMME_ARCH=arm GIMME_GOARM=7
go:
- '1.10'
script:
- export ARCH=arm
- export ARM=7
- cd traffic
- go build -ldflags "-s -w"
deploy:
  provider: releases
  api_key:
    secure: G75zG2Abp2ThYYy3CUVvmdWSxA5UblDvvkFmk8a9E+xRn6nITuiwVonrwVg5+4dpLY621+GF0Ra8PR7gprMHe9TFCsIksRcWy6FpWjPXrtxgQw2W6DlAcK+4rZNQ+AtQJulh0Bj55jY05qOpN3p2n+eCH3vJyNEzZYwSQCBiKpZkGwgB4tp0FCuKreklaewCVIXM76eEKgnFpkvBnmcWqVd72ddCZ4u/W2cTzTPl49jAGwGtNxGnfdMGmmBWGKU9ynR6qIeWixsZZ8A5+56go0ZTp4W0Svh0OXBjinOWR35a43kqoAScHvdDPfHxaaDD8MQz0wzJ4k6ApogoZVqYd3KwL75ILQ8Q7Ye04oyMp3EES5EMsdKvHG10D3dUkx1SEIQ0nH3MpX0/9duiwzZkbN32ZFcHTvFOGHk69pyZt4JY+hdpjI9TzkwNRrea7HN8RoxW103ZxqbQNdG3ONlBzfcab5QTw4SucL9/hbIXuZgmeUju2F08eataeA8qJLtSbGsSGSgz4Anar7OdTqplSd3IJnL7zXXKXniDGowj287RPA2sTDeBhaYO93qZSUHEB/KfgaaqFfX8MKTRIUsfLsolpfD0JLuSzHrOVeELjMro0HT7W/op6gOIBtXpiovMh/9qrsQFumsGZGzdP32DRY0e7EVxsjO5HgFn4CkOozs=
  file: traffic
  skip_cleanup: true